src/main/java/io/github/cottonmc/cotton/gui/client/ScreenDrawing.java
src/main/java/io/github/cottonmc/cotton/gui/client/modmenu/ConfigGui.java
src/main/java/io/github/cottonmc/cotton/gui/widget/WWidget.java
src/main/resources/assets/libgui/lang/en_us.json

Changes proposed in this pull request:
- Fixes one of ScreenDrawing.rect()'s overloads ignoring the color parameter
- Replaces `option.libgui.done` with vanilla's `gui.done`
- Uncomments WWidget.setParent()

Some tweaks

---

src/main/java/io/github/cottonmc/cotton/gui/widget/WButton.java

Adds an `active` flag to `WButton` (name copied from Yarn) that controls button appearance and also disables any clicking effects if the button is not active.
Also changed the colors in `WButton.paintForeground` to hex for readability.

Button disabling

---

src/main/java/io/github/cottonmc/cotton/gui/widget/WWidget.java

Changes proposed in this pull request:
- Fix the `WWidget.renderForeground` tooltip position

Fix tooltip position

---

build.gradle
gradle.properties
src/main/java/io/github/cottonmc/cotton/gui/client/ScreenDrawing.java
src/main/java/io/github/cottonmc/cotton/gui/widget/WTextField.java

Just some mapping changes. I also changed the `==` for project name comparison to `equalsIgnoreCase` so a freshly cloned LibGui project sets up Loom properly.

Update to 19w46b

---

GuiTest/src/main/java/io/github/cottonmc/test/client/TestClientGui.java
src/main/java/io/github/cottonmc/cotton/gui/widget/WSprite.java
src/main/java/io/github/cottonmc/cotton/gui/widget/WTiledSprite.java

This PR adds a new `WTiledSprite` that renders the same as `WSprite` but tiles the texture according to a tiledWidth and tiledHeight setting.
I implemented this by moving the actual draw functionality in `WSprite` into a method called `paintFrame`. I did this to avoid duplicate code, so `WTiledSprite` only has to overwrite that method.
Keep in mind that this is my first contribution to any minecraft mod, the code might be crap.
I also tried to follow your [contributing guidelines](https://github.com/CottonMC/.github/blob/master/CONTRIBUTING.md#pull-requests) but the link to the ["instructions in the template"](https://github.com/CottonMC/.github/blob/master/PULL_REQUEST_TEMPLATE.md) is broken.

implement a WTiledSprite widget

---

src/main/java/io/github/cottonmc/cotton/gui/client/ScreenDrawing.java

This adds the ability to draw a texture with a given opacity to the `ScreenDrawing.texturedRect` method.
The overloads are kinda messy, but i don't know a better way. Maybe the builder pattern could help here? (for a future version)

ScreenDrawing: add ability to draw opaque textures

---

src/main/java/io/github/cottonmc/cotton/gui/widget/WTiledSprite.java

makes this widget easier to extend
we could also just make `tileWidth` and `tileHeight` public and remove all getters and settings, but i guess that's bad java..?

tiled-sprite: introduce getters for tileWidth/height

---

src/main/java/io/github/cottonmc/cotton/gui/widget/data/Color.java

allows to interpolate colors on RGB objects. can be used for gradients for example.
I copied the method head & parts of the description from here: https://docs.oracle.com/javase/8/javafx/api/javafx/scene/paint/Color.html#interpolate-javafx.scene.paint.Color-double-

RGB: add interpolate method

---

src/main/java/io/github/cottonmc/cotton/gui/widget/data/Color.java

simple helper so rgb colors can be created without specifying an alpha value.

RGB add simpler constructor without alpha

---

src/main/java/io/github/cottonmc/cotton/gui/SyncedGuiDescription.java

This fixes shift clicking into a slot with a max stack amount less than the item's max stack amount.

Fix SyncedGuiDescription.insertIntoExisting Not Respecting the Slot Max Stack Amount

---

src/main/java/io/github/cottonmc/cotton/gui/widget/WScrollBar.java

Use the movable area (ie. scroll bar length minus handle length) instead of just the scroll bar length.
This makes it so the handle actually feels like it's sticking to the cursor while scrolling.

WScrollBar: More intuitive drag scroll threshold

---

src/main/java/io/github/cottonmc/cotton/gui/SyncedGuiDescription.java

LibGUI overrides the behaviour for QUICK_MOVE and uses Slot#getMaxItemCount() instead of Slot#getMaxItemCount(ItemStack) which makes it ignore if you want a different limit for a specific item and is also inconsistent with vanilla behaviour. I've tested it and it works

Use Slot#getMaxItemCount(ItemStack) instead of Slot#getMaxItemCount()

---

src/main/java/io/github/cottonmc/cotton/gui/widget/WScrollPanel.java

Basically it would spam the log (and thanks to visual stuff, the logger) with unfocused stuff about WScrollPanel. That is because WScrollBar would call request when touched, but it had not been validated. This fixes that with a two line fix.

Fix WScrollPanel validation issue

---

src/main/java/io/github/cottonmc/cotton/gui/client/ScreenDrawing.java

In pre-1.17 LibGui versions, `texturedRect()` was able to blend transparent textures with alpha values between 0 and 1.
Here's some comparison screenshots between 1.17 and 1.16 versions: https://github.com/minepkg/test-utils/pull/6#issuecomment-880955356
This is a regression from https://github.com/CottonMC/LibGui/commit/c321cfc512e7277f934276657ca21b89cae84794#diff-33951c5440c0f9d174429cbffd7b5657d69486889a3e70b4ae750c360a3da8ecL146 which removed the call to `RenderSystem.enableBlend()`.
The fix is to simply add the blend calls back in.

Fix texturedRect() not blending transparent textures

---

GuiTest/src/main/java/io/github/cottonmc/test/TestDescription.java
src/main/java/io/github/cottonmc/cotton/gui/widget/WTextField.java

Potentially fixes #139
Functionality changes made to `WTextField`:
- Introduce text scrolling
- Fix CTRL+Movement key movement
- General refactoring

Improve WTextField

---

src/main/java/io/github/cottonmc/cotton/gui/widget/WListPanel.java

The change fixes the problem that the last element/elements in the list are not shown because the margin spaces weren't properly calculated in the visibleCells variable.
Removed unnecessary for-loop run-trough.

Corrected calculation of the current visible elements in the list panel.

---

GuiTest/src/main/java/io/github/cottonmc/test/client/LibGuiTestClient.java
GuiTest/src/main/java/io/github/cottonmc/test/client/PaddingTestGui.java
GuiTest/src/main/java/io/github/cottonmc/test/client/TestClientGui.java
src/main/java/io/github/cottonmc/cotton/gui/widget/WGridPanel.java

I added those as static constructors, since managing regular constructor overloads with just a bunch of int arguments didn't work out.

Allow WGridPanel to have gaps between widgets.

---

src/main/java/io/github/cottonmc/cotton/gui/widget/WItem.java

When I tried to display items in `WGridPanel` through `WItem`, they have an obvious position deviation, which is unexpected.
As you can see, all the items displayed above have an one pixel offset by the both direction(x and y). That means the preset position of `WItem` in Grid may be undesirable. 
This small change makes user displaying item in slot image more convenient.

Optimize WItem display position offset

---

src/main/java/io/github/cottonmc/cotton/gui/widget/WBox.java

Currently there is a bug where a WBox with
* `axis` = HORIZONTAL
* `horizontalAlignment` = LEFT
* `verticalAlignment` = CENTER or BOTTOM
will receive an incorrect horizontal offset ('dimension')
This PR resolves that bug.

Fix WBox Horizontal Offset

---

gradle.properties
src/main/java/io/github/cottonmc/cotton/gui/ValidatedSlot.java
src/main/java/io/github/cottonmc/cotton/gui/widget/WItemSlot.java
src/main/java/io/github/cottonmc/cotton/gui/widget/WPlayerInvPanel.java
src/testMod/java/io/github/cottonmc/test/TestDescription.java

- Deprecates `WItemSlot`'s filter system in favor of input and output filters;
- The test mod is updated to test this.
- Weaken `WPlayerInvPanel`'s components (`inv`, `hotbar` and `label`) from `private` to `protected;
- Bump some dependencies, as the test mod wouldn't launch without it.

Add input/output filter + weaken WPlayerInvPanel's components' protection

---

src/main/java/io/github/cottonmc/cotton/gui/widget/WScrollPanel.java

Adds getters for the vertical and horizontal scroll bars to `WScrollPanel`, which is useful for things like changing the scroll bar's speed.
~~Not sure if we want to have setters as well? let me know if that's the case and I can add that in.~~ Setters have been added.

Add scroll bar getters to `WScrollPanel`

---

src/main/java/io/github/cottonmc/cotton/gui/widget/WSprite.java

Currently WSprite doesn't work correctly: it ignores the last frame because of a typo / duplicated check in .paint()

Fix multiframe WSprite

---

build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties
src/main/java/io/github/cottonmc/cotton/gui/SyncedGuiDescription.java
src/main/java/io/github/cottonmc/cotton/gui/impl/ScreenNetworkingImpl.java
src/main/java/io/github/cottonmc/cotton/gui/impl/client/LibGuiClient.java
src/main/resources/fabric.mod.json
src/testMod/java/io/github/cottonmc/test/GuiBlock.java
src/testMod/java/io/github/cottonmc/test/GuiItem.java
src/testMod/java/io/github/cottonmc/test/LibGuiTest.java
src/testMod/java/io/github/cottonmc/test/NoBlockInventoryBlock.java

Depends on <https://github.com/CottonMC/Jankson-Fabric/pull/23> (or similar)
For the new networking paradigm, I chose to keep the extra `PacketByteBuf` data intact to preserve API. A much more robust system would be to use `PacketCodec`s for that system as well

Update to 1.20.6

---

src/main/java/io/github/cottonmc/cotton/gui/widget/WDynamicLabel.java
src/main/java/io/github/cottonmc/cotton/gui/widget/WLabel.java
src/main/java/io/github/cottonmc/cotton/gui/widget/WText.java

Add option for WLabel, WText and WDynamicLabel to have shadows

---

src/main/java/io/github/cottonmc/cotton/gui/widget/WDynamicLabel.java

Add vertical alignment to WDynamicLabel
